# Generated by Django 6.0.3 on 2026-03-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
        ('empresas', '0003_contribuyente_alter_empresa_ruc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Contacto',
        ),
    ]
