# Generated by Django 6.0.3 on 2026-03-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_alter_tarea_fecha_fin_alter_tarea_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='empresa',
            new_name='contacto',
        ),
    ]
