# Generated by Django 6.0.3 on 2026-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_rename_empresa_tarea_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
