# Generated by Django 6.0.3 on 2026-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_tarea_titulo_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
