# Generated by Django 6.0.3 on 2026-03-10 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(4)])),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
    ]
